# ComfyUI Docker Compose File v1.0.1 by John Aldred
# http://www.johnaldred.com
# http://github.com/kaouthia

services:
  comfyui:
    build:
      dockerfile: Dockerfile
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      # persist your models, output, and settings:
      - /nvme/comfyui_models/models:/app/ComfyUI/models

      # persist your output images:
      - /6to/comfyUI-output:/app/ComfyUI/output
      
      # persist all your settings & extra nodes:
      - /home/fahim/docker/comfyui/settings:/app/ComfyUI/user/default:rw

      # persist just your saved flows (overrides the workflows/ in default):
      - /home/fahim/docker/comfyui/workflows:/app/ComfyUI/user/default/workflows:rw
    
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
    restart: unless-stopped
