# ComfyUI Docker Compose File v1.0.1 by John Aldred
# http://www.johnaldred.com
# http://github.com/kaouthia

services:
  comfyk:
    build:
      dockerfile: Dockerfile
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      # persist your models:
      - c:/home/user/comfyui/models:/app/ComfyUI/models:rw

      # load your input content:
      - c:/home/user/comfyui/input:/app/ComfyUI/input:rw

      # persist your output content:
      - c:/home/user/comfyui/output:/app/ComfyUI/output:rw
      
      # persist user settings:
      - c:/home/user/comfyui/user:/app/ComfyUI/user:rw
    
    # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
    restart: unless-stopped
